'Hal\Core\Entity\JobType\Build':
    table: 'jobs_builds'
    repositoryClass: 'Hal\Core\Repository\JobType\BuildRepository'
    type: 'entity'

    # id:
    #     id:
    #         column: 'id'
    #         type: 'guid'

    fields:

        reference:
            column: 'code_reference'
            column: 'status'
            type: 'string'
            length: 100

        commit:
            column: 'code_commit_sha'
            type: 'string'
            length: 100

        # created:
        #     column: 'created'
        #     type: 'timepoint'

    manyToOne:

        application:
            cache: { usage : READ_ONLY }
            targetEntity: 'Hal\Core\Entity\Application'
            joinColumn:
                name: 'application_id'
                referencedColumnName: 'id'
                nullable: true

        environment:
            cache: { usage : READ_ONLY }
            targetEntity: 'Hal\Core\Entity\Environment'
            joinColumn:
                name: 'environment_id'
                referencedColumnName: 'id'
                nullable: true
