'Hal\Core\Entity\JobType\Build':
    table: 'jobs_builds'
    repositoryClass: 'Hal\Core\Repository\BuildRepository'
    type: 'entity'

    id:
        id:
            column: 'id'
            type: 'guid'

    fields:

        reference:
            column: 'code_reference'
            column: 'status'
            type: 'string'
            length: 100

        commit:
            column: 'code_commit_sha'
            type: 'string'
            length: 100

        created:
            column: 'created'
            type: 'timepoint'

    manyToOne:

        application:
            cache: { usage : READ_ONLY }
            targetEntity: 'Application'
            joinColumn:
                name: 'application_id'
                referencedColumnName: 'id'
                nullable: true

        environment:
            cache: { usage : READ_ONLY }
            targetEntity: 'Environment'
            joinColumn:
                name: 'environment_id'
                referencedColumnName: 'id'
                nullable: true
