'Hal\Core\Entity\JobType\Release':
    table: 'jobs_releases'
    repositoryClass: 'Hal\Core\Repository\JobType\ReleaseRepository'
    type: 'entity'

    # id:
    #     id:
    #         column: 'id'
    #         type: 'guid'

    # fields:

    #     created:
    #         column: 'created'
    #         type: 'timepoint'

    manyToOne:

        build:
            cache: { usage : READ_ONLY }
            targetEntity: 'Build'
            joinColumn:
                name: 'build_id'
                referencedColumnName: 'id'
                nullable: false

        application:
            cache: { usage : READ_ONLY }
            targetEntity: 'Hal\Core\Entity\Application'
            joinColumn:
                name: 'application_id'
                referencedColumnName: 'id'
                nullable: true

        environment:
            cache: { usage : READ_ONLY }
            targetEntity: 'Hal\Core\Entity\Environment'
            joinColumn:
                name: 'environment_id'
                referencedColumnName: 'id'
                nullable: true

        target:
            cache: { usage : READ_ONLY }
            targetEntity: 'Hal\Core\Entity\Target'
            joinColumn:
                name: 'target_id'
                referencedColumnName: 'id'
                nullable: true

