language: php

sudo: require

php:
  - 7.1

before_install:
    - 'sudo add-apt-repository -y ppa:chris-lea/libsodium'
    - 'sudo apt-get -q update'
    - 'sudo apt-get -y install libsodium-dev'
    - 'pecl install libsodium'

install:
    - travis_retry composer --no-interaction --no-progress install
    - composer show --installed

script: vendor/bin/phpunit
