# https://circleci.com/docs/2.0/language-php/
# https://circleci.com/docs/2.0/circleci-images/
version: 2
jobs:
  build:
    docker:
      - 'image': 'circleci/php:7.1.8'

    working_directory: '~/project'

    steps:
      - 'checkout'

      - 'run': 'pecl install libsodium'

      # Download and cache dependencies
      - 'restore_cache':
          keys:
            - 'v1-dependencies-{{ checksum "composer.json" }}'
            - 'v1-dependencies-' # fallback to using the latest cache if no exact match is found

      - 'run': 'composer self-update'
      - 'run': 'composer --no-interaction --no-progress install'

      - 'save_cache':
          key: 'v1-dependencies-{{ checksum "composer.json" }}'
          paths:
            - './vendor'

      - 'run': './vendor/bin/phpunit'
