# https://circleci.com/docs/2.0/language-php/
# https://circleci.com/docs/2.0/circleci-images/
version: 2
jobs:
    build:
        docker:
            - 'image': 'halplatform/php:latest'

        working_directory: '~/project'

        steps:
            - checkout

            - restore_cache:
                keys:
                    - 'v1-dependencies-{{ checksum "composer.json" }}'
                    - 'v1-dependencies-' # fallback to using the latest cache if no exact match is found

            - run:
                name: 'Update Composer'
                command: 'composer self-update'

            - run:
                name: 'Install packages'
                command: 'composer --no-interaction --no-progress install'

            - run:
                name: 'List installed packages'
                command: 'composer show'

            - save_cache:
                key: 'v1-dependencies-{{ checksum "composer.json" }}'
                paths:
                    - './vendor'

            - run:
                name: 'Run tests'
                command: './vendor/bin/phpunit'
