QL\Hal\Core\Entity\Deployment:
    type: entity
    repositoryClass: QL\Hal\Core\Repository\DeploymentRepository
    table: Deployments

    cache: {usage : NONSTRICT_READ_WRITE}

    id:
        id:
            column: DeploymentId
            type: integer
            generator:
                strategy: AUTO

    fields:

        name:
            column: DeploymentName
            type: string
            length: 80

        url:
            column: DeploymentUrl
            type: string
            length: 200

        path:
            column: DeploymentPath
            type: string
            length: 200
            nullable: true

        cdName:
            column: DeploymentCDName
            type: string
            length: 100
            nullable: true
        cdGroup:
            column: DeploymentCDGroup
            type: string
            length: 100
            nullable: true
        cdConfiguration:
            column: DeploymentCDConfiguration
            type: string
            length: 100
            nullable: true

        ebName:
            column: DeploymentEbName
            type: string
            length: 100
            nullable: true
        ebEnvironment:
            column: DeploymentEbEnvironment
            type: string
            length: 100
            nullable: true

        ec2Pool:
            column: DeploymentEc2Pool
            type: string
            length: 100
            nullable: true

        s3bucket:
            column: DeploymentS3Bucket
            type: string
            length: 100
            nullable: true
        s3file:
            column: DeploymentS3File
            type: string
            length: 100
            nullable: true

    manyToOne:

        application:
            cache: {usage : READ_ONLY}
            targetEntity: Application
            joinColumn:
                name: RepositoryId
                referencedColumnName: RepositoryId

        server:
            cache: {usage : READ_ONLY}
            targetEntity: Server
            inversedBy: deployments
            joinColumn:
                name: ServerId
                referencedColumnName: ServerId

        credential:
            cache: {usage : NONSTRICT_READ_WRITE}
            targetEntity: Credential
            joinColumn:
                name: CredentialId
                referencedColumnName: CredentialId
