QL\Kraken\Core\Entity\Application:
    type: entity
    table: KrakenApplication

    cache: {usage : NONSTRICT_READ_WRITE}

    id:
        id:
            column: ApplicationID
            type: string
            length: 32
            options: {fixed: true}

    fields:

        coreId:
            column: ApplicationCoreID
            type: string
            length: 32
        name:
            column: ApplicationName
            type: string
            length: 64

    manyToOne:

        halApplication:
            cache: {usage : READ_ONLY}
            targetEntity: QL\Hal\Core\Entity\Application
            joinColumn:
                name: HalApplicationID
                referencedColumnName: RepositoryId
                nullable: true
