QL\Kraken\Core\Entity\Configuration:
    type: entity
    repositoryClass: QL\Kraken\Core\Repository\ConfigurationRepository
    table: KrakenConfiguration

    cache: {usage : NONSTRICT_READ_WRITE}

    id:
        id:
            column: ConfigurationID
            type: string
            length: 32
            options: {fixed: true}

    fields:

        isSuccess:
            column: ConfigurationStatus
            type: boolean
        audit:
            column: ConfigurationAudit
            type: text
            length: 65535
        created:
            column: ConfigurationCreated
            type: timepoint
            nullable: true

    manyToOne:

        application:
            cache: {usage : READ_ONLY}
            targetEntity: Application
            joinColumn:
                name: ApplicationID
                referencedColumnName: ApplicationID

        environment:
            cache: {usage : READ_ONLY}
            targetEntity: Environment
            joinColumn:
                name: EnvironmentID
                referencedColumnName: EnvironmentID

        user:
            cache: {usage : READ_ONLY}
            targetEntity: QL\Hal\Core\Entity\User
            joinColumn:
                name: UserID
                referencedColumnName: UserId
