parameters:
  doctrine.devmode:   true
  doctrine.connection:
    driver:     pdo_mysql
    host:       $DB_SERVER_NAME
    user:       $DB_USER_NAME
    password:   $DB_PASSWORD
    dbname:     $DB_NAME

