services:

    # Doctrine Configuration
    doctrine.config:
        class: 'Doctrine\ORM\Configuration'
        factory_class: 'Doctrine\ORM\Tools\Setup'
        factory_method: 'createAnnotationMetadataConfiguration'
        arguments:
            - [@doctrine.mapping]
            - %doctrine.devmode%

    doctrine.mapping:
        class: 'DOES_NOT_MATTER'
        factory_class: 'QL\Hal\Core\EntityMapping'
        factory_method: 'path'

    # Doctrine Entity Manager Configurator
    doctrine.em.config:
        class: 'QL\Hal\Core\Entity\Configurator\EntityManagerConfigurator'

    # Doctrine Event Manager
    doctrine.events:
        class: 'Doctrine\Common\EventManager'

    # Doctrine Entity Manager
    doctrine.em:
        class: 'Doctrine\ORM\EntityManager'
        factory_class: 'Doctrine\ORM\EntityManager'
        factory_method: 'create'
        arguments:
            - %doctrine.connection%
            - @doctrine.config
            - @doctrine.events
        configurator: [@doctrine.em.config, 'configure']

    # Build Repository
    build.repo:
        class: 'QL\Hal\Core\Entity\Repository\BuildRepository'
        factory_service: 'doctrine.em'
        factory_method: 'getRepository'
        arguments: ['QL\Hal\Core\Entity\Build']

    # Consumer Repository
    consumer.repo:
        class:            'QL\Hal\Core\Entity\Repository\ConsumerRepository'
        factory_service: 'doctrine.em'
        factory_method: 'getRepository'
        arguments: ['QL\Hal\Core\Entity\Consumer']

    # Deployment Repository
    deployment.repo:
        class: 'QL\Hal\Core\Entity\Repository\DeploymentRepository'
        factory_service: 'doctrine.em'
        factory_method: 'getRepository'
        arguments: ['QL\Hal\Core\Entity\Deployment']

    # Environment Repository
    environment.repo:
        class: 'QL\Hal\Core\Entity\Repository\EnvironmentRepository'
        factory_service: 'doctrine.em'
        factory_method: 'getRepository'
        arguments: ['QL\Hal\Core\Entity\Environment']

    # Group Repository
    group.repo:
        class: 'QL\Hal\Core\Entity\Repository\GroupRepository'
        factory_service: 'doctrine.em'
        factory_method: 'getRepository'
        arguments: ['QL\Hal\Core\Entity\Group']

    # Push Repository
    push.repo:
        class: 'QL\Hal\Core\Entity\Repository\PushRepository'
        factory_service: 'doctrine.em'
        factory_method: 'getRepository'
        arguments: ['QL\Hal\Core\Entity\Push']

    # Repository Repository
    repository.repo:
        class:            'QL\Hal\Core\Entity\Repository\RepositoryRepository'
        factory_service: 'doctrine.em'
        factory_method: 'getRepository'
        arguments: ['QL\Hal\Core\Entity\Repository']

    # Server Property Repository
    serverproperty.repo:
        class: 'QL\Hal\Core\Entity\Repository\ServerPropertyRepository'
        factory_service: 'doctrine.em'
        factory_method: 'getRepository'
        arguments: ['QL\Hal\Core\Entity\ServerProperty']

    # Server Repository
    server.repo:
        class: 'QL\Hal\Core\Entity\Repository\ServerRepository'
        factory_service: 'doctrine.em'
        factory_method: 'getRepository'
        arguments: ['QL\Hal\Core\Entity\Server']

    # Session Repository
    session.repo:
        class: 'QL\Hal\Core\Entity\Repository\SessionRepository'
        factory_service: 'doctrine.em'
        factory_method: 'getRepository'
        arguments: ['QL\Hal\Core\Entity\Session']

    # Subscription Repository
    subscription.repo:
        class: 'QL\Hal\Core\Entity\Repository\SubscriptionRepository'
        factory_service: 'doctrine.em'
        factory_method: 'getRepository'
        arguments: ['QL\Hal\Core\Entity\Subscription']

    # User Repository
    user.repo:
        class: 'QL\Hal\Core\Entity\Repository\UserRepository'
        factory_service: 'doctrine.em'
        factory_method: 'getRepository'
        arguments: ['QL\Hal\Core\Entity\User']

    # Token Repository
    token.repo:
        class: 'QL\Hal\Core\Entity\Repository\TokenRepository'
        factory_service: 'doctrine.em'
        factory_method: 'getRepository'
        arguments: ['QL\Hal\Core\Entity\Token']

    # Audit Log Repository
    audit.log.repo:
        class: 'QL\Hal\Core\Entity\Repository\LogRepository'
        factory_service: 'doctrine.em'
        factory_method: 'getRepository'
        arguments: ['QL\Hal\Core\Entity\AuditLog']

    # Log Repository
    event.log.repo:
        class: 'Doctrine\ORM\EntityRepository'
        factory_service: 'doctrine.em'
        factory_method: 'getRepository'
        arguments: ['QL\Hal\Core\Entity\EventLog']
