parameters:
    # default parameters
    doctrine.devmode: false
    doctrine.proxy.dir: '.doctrine'
    doctrine.connection:
        driver: 'pdo_mysql'
        host: 'localhost'
        user: 'root'
        password: ''
        dbname: 'hal'

    doctrine.lvl2cache.ttl: 600
    doctrine.lvl2cache.lock: 60

services:

    ####################################################################################################################
    # DOCTRINE PATHS
    ####################################################################################################################

    doctrine.mapping.dir:
        class: 'stdClass'
        factory: ['QL\Hal\Core\DoctrineFactory', 'yamlPath']

    doctrine.proxy.dir:
        class: 'stdClass'
        factory: ['QL\Hal\Core\DoctrineFactory', 'doctrineProxyPath']
        arguments: [%doctrine.proxy.dir%]

    ####################################################################################################################
    # DOCTRINE CORE
    ####################################################################################################################

    # Doctrine Entity Manager
    doctrine.em:
        class: 'Doctrine\ORM\EntityManager'
        factory: ['Doctrine\ORM\EntityManager', 'create']
        arguments:
            - %doctrine.connection%
            - @doctrine.config
            - @doctrine.em.events
        configurator: [@doctrine.em.configurator, 'configure']

    doctrine.config:
        class: 'Doctrine\ORM\Configuration'
        factory: ['Doctrine\ORM\Tools\Setup', 'createConfiguration']
        arguments:
            - %doctrine.devmode%
            - @doctrine.proxy.dir
            - @cache.doctrine
        calls:
            - ['setMetadataDriverImpl', [@doctrine.config.driver]]
            - ['setSecondLevelCacheEnabled', [true]]
            - ['setSecondLevelCacheConfiguration', [@doctrine.secondlevelcache.config]]

    doctrine.config.driver:
        class: 'Doctrine\ORM\Mapping\Driver\SimplifiedYamlDriver'
        factory: ['QL\Hal\Core\DoctrineFactory', 'buildConfigurationDriver']
        arguments: [@doctrine.mapping.dir]

    doctrine.em.configurator:
        class: 'QL\Hal\Core\DoctrineConfigurator'
    doctrine.em.events:
        class: 'Doctrine\Common\EventManager'

    ####################################################################################################################
    # DOCTRINE CACHE
    ####################################################################################################################

    # default to array
    doctrine.cache:
        class: 'Doctrine\Common\Cache\ArrayCache'

    doctrine.secondlevelcache.config:
        class: 'Doctrine\ORM\Cache\CacheConfiguration'
        calls:
            - ['setCacheFactory', [@doctrine.secondlevelcache.factory]]

    doctrine.secondlevelcache.factory:
        class: 'Doctrine\ORM\Cache\DefaultCacheFactory'
        arguments: [@doctrine.secondlevelcache.region.config, @cache.doctrine]

    doctrine.secondlevelcache.region.config:
        class: 'Doctrine\ORM\Cache\RegionsConfiguration'
        arguments: [%doctrine.lvl2cache.ttl%, %doctrine.lvl2cache.lock%]

    ####################################################################################################################
    # DOCTRINE HELPERS
    ####################################################################################################################

    doctrine.random.id:
        class: 'QL\Hal\Core\RandomGenerator'

    ####################################################################################################################
    # REPOSITORIES
    ####################################################################################################################

    # Build Repository
    build.repo:
        class: 'QL\Hal\Core\Repository\BuildRepository'
        factory: [@doctrine.em, 'getRepository']
        arguments: ['QL\Hal\Core\Entity\Build']

    # Consumer Repository
    consumer.repo:
        class: 'QL\Hal\Core\Repository\ConsumerRepository'
        factory: [@doctrine.em, 'getRepository']
        arguments: ['QL\Hal\Core\Entity\Consumer']

    # Deployment Repository
    deployment.repo:
        class: 'QL\Hal\Core\Repository\DeploymentRepository'
        factory: [@doctrine.em, 'getRepository']
        arguments: ['QL\Hal\Core\Entity\Deployment']

    # Environment Repository
    environment.repo:
        class: 'QL\Hal\Core\Repository\EnvironmentRepository'
        factory: [@doctrine.em, 'getRepository']
        arguments: ['QL\Hal\Core\Entity\Environment']

    # Group Repository
    group.repo:
        class: 'QL\Hal\Core\Repository\GroupRepository'
        factory: [@doctrine.em, 'getRepository']
        arguments: ['QL\Hal\Core\Entity\Group']

    # Push Repository
    push.repo:
        class: 'QL\Hal\Core\Repository\PushRepository'
        factory: [@doctrine.em, 'getRepository']
        arguments: ['QL\Hal\Core\Entity\Push']

    # Repository Repository
    repository.repo:
        class: 'QL\Hal\Core\Repository\RepositoryRepository'
        factory: [@doctrine.em, 'getRepository']
        arguments: ['QL\Hal\Core\Entity\Repository']

    # Server Repository
    server.repo:
        class: 'QL\Hal\Core\Repository\ServerRepository'
        factory: [@doctrine.em, 'getRepository']
        arguments: ['QL\Hal\Core\Entity\Server']

    # User Repository
    user.repo:
        class: 'QL\Hal\Core\Repository\UserRepository'
        factory: [@doctrine.em, 'getRepository']
        arguments: ['QL\Hal\Core\Entity\User']

    # Token Repository
    token.repo:
        class: 'QL\Hal\Core\Repository\TokenRepository'
        factory: [@doctrine.em, 'getRepository']
        arguments: ['QL\Hal\Core\Entity\Token']

    # Audit Log Repository
    audit.log.repo:
        class: 'QL\Hal\Core\Repository\AuditLogRepository'
        factory: [@doctrine.em, 'getRepository']
        arguments: ['QL\Hal\Core\Entity\AuditLog']

    # Event Log Repository
    event.log.repo:
        class: 'QL\Hal\Core\Repository\EventLogRepository'
        factory: [@doctrine.em, 'getRepository']
        arguments: ['QL\Hal\Core\Entity\EventLog']

    # Encrypted Property Repository
    encrypted.repo:
        class: 'QL\Hal\Core\Repository\EncryptedPropertyRepository'
        factory: [@doctrine.em, 'getRepository']
        arguments: ['QL\Hal\Core\Entity\EncryptedProperty']
