
# Pushes Table
Push:
  type:   entity
  table:  Pushes
  fields:
    id:
      column:       PushId
      type:         integer
      unique:       true
      generator:
        strategy:   AUTO
    start:
      column:       PushStart
      type:         datetime
      nullable:     true
    end:
      column:       PushEnd
      type:         datetime
      nullable:     true
    status:
      column:       PushStatus
      type:         string
    oneToOne:
      user:
        nullable:               true
        targetEntity:           User
        joinColumn:
          name:                 UserId
          referencedColumnName: UserId
      consumer:
        nullable:               true
        targetEntity:           Consumer
        joinColumn:
          name:                 ConsumerId
          referencedColumnName: ConsumerId
      build:
        targetEntity:           Build
        joinColumn:
          name:                 BuildId
          referencedColumnName: BuildId
      deployment:
        targetEntity:           Deployment
        joinColumn:
          name:                 DeploymentId
          referencedColumnName: DeploymentId

