'Hal\Core\Entity\System\VersionControlProvider':
    table: 'system_vcs_providers'
    type: 'entity'

    cache: { usage : NONSTRICT_READ_WRITE }

    id:
        id:
            column: 'id'
            type: 'guid'

    fields:

        name:
            column: 'name'
            type: 'string'
            length: 100

        type:
            column: 'vcs_type'
            type: 'string'
            length: 50
            options: { default: 'ghe' } # See VCSProviderEnum for list of options

        parameters:
            column: 'parameters'
            type: 'json_array'

        created:
            column: 'created'
            type: 'timepoint'
