'Hal\Core\Entity\User\UserPermission':
    table: 'users_permissions'
    type: 'entity'

    cache: { usage : NONSTRICT_READ_WRITE }

    id:
        id:
            column: 'id'
            type: 'guid'

    fields:

        type:
            column: 'permission_type'
            type: 'string'
            length: 20
            options: { default: 'member' } # See UserPermissionEnum for list of options

        created:
            column: 'created'
            type: 'timepoint'

    manyToOne:

        user:
            cache: { usage : READ_ONLY }
            targetEntity: 'User'
            joinColumn:
                name: 'user_id'
                referencedColumnName: 'id'
                nullable: false

        application:
            cache: { usage : READ_ONLY }
            targetEntity: 'Application'
            joinColumn:
                name: 'application_id'
                referencedColumnName: 'id'
                nullable: true

        organization:
            cache: { usage : READ_ONLY }
            targetEntity: 'Organization'
            joinColumn:
                name: 'organization_id'
                referencedColumnName: 'id'
                nullable: true

        environment:
            cache: { usage : READ_ONLY }
            targetEntity: 'Environment'
            joinColumn:
                name: 'environment_id'
                referencedColumnName: 'id'
                nullable: true
