'Hal\Core\Entity\Credential\AWSRoleCredential':
    type: 'embeddable'

    fields:

        account:
            column: 'awsrole_account'
            type: 'string'
            length: 25
        role:
            column: 'awsrole_role'
            type: 'string'
            length: 100
