'Hal\Core\Entity\Credential\AWSStaticCredential':
    type: 'embeddable'

    fields:

        key:
            column: 'awsstatic_key'
            type: 'string'
            length: 100
        secret:
            column: 'awsstatic_secret'
            type: 'string'
