'Hal\Core\Entity\Credential\PrivateKeyCredential':
    type: 'embeddable'

    fields:

        username:
            column: 'privatekey_username'
            type: 'string'
            length: 100
        path:
            column: 'privatekey_path'
            type: 'string'
            length: 200
        file:
            column: 'privatekey_file'
            type: 'string'
