'Hal\Core\Entity\Application\GitHubApplication':
    type: 'embeddable'

    fields:

        owner:
            column: 'owner'
            type: 'string'
            length: 100
        repository:
            column: 'repository'
            type: 'string'
            length: 100
