'Hal\Core\Entity\Application':
    table: 'applications'
    repositoryClass: 'Hal\Core\Repository\ApplicationRepository'
    type: 'entity'

    cache: { usage : NONSTRICT_READ_WRITE }

    id:
        id:
            column: 'id'
            type: 'guid'

    fields:

        name:
            column: 'name'
            type: 'string'
            length: 100

        parameters:
            column: 'parameters'
            type: 'json_array'

        isDisabled:
            column: 'is_disabled'
            type: 'boolean'
            options: { default: false }

        created:
            column: 'created'
            type: 'timepoint'

    manyToOne:

        provider:
            cache: { usage : READ_ONLY }
            fetch: EAGER
            targetEntity: 'Hal\Core\Entity\System\VersionControlProvider'
            joinColumn:
                name: 'provider_id'
                referencedColumnName: 'id'
                nullable: true

        organization:
            cache: { usage : READ_ONLY }
            targetEntity: 'Organization'
            joinColumn:
                name: 'organization_id'
                referencedColumnName: 'id'
                nullable: true
