'Hal\Core\Entity\Application':
    table: 'applications'
    repositoryClass: 'Hal\Core\Repository\ApplicationRepository'
    type: 'entity'

    cache: {usage : NONSTRICT_READ_WRITE}

    id:
        id:
            column: 'id'
            type: 'guid'

    fields:

        identifier:
            column: 'identifier'
            type: 'string'
            length: 30
            unique: true
        name:
            column: 'name'
            type: 'string'
            length: 100

    embedded:

        gitHub:
            class: 'Hal\Core\Entity\Application\GitHubApplication'
            columnPrefix: false

    manyToOne:

        organization:
            cache: {usage : READ_ONLY}
            targetEntity: 'Organization'
            joinColumn:
                name: 'organization_id'
                referencedColumnName: 'id'
                nullable: true
