'Hal\Core\Entity\AuditEvent':
    table: 'audit_events'
    repositoryClass: 'Hal\Core\Repository\AuditEventRepository'
    type: 'entity'

    cache: { usage : READ_ONLY }

    id:
        id:
            column: 'id'
            type: 'guid'

    fields:

        action:
            column: 'action'
            type: 'string'
            length: 100
            options: { default: 'create' } # See AuditActionEnum for list of options

        actor:
            column: 'actor'
            type: 'string'
            length: 100

        description:
            column: 'description'
            type: 'string'
            length: 200

        parameters:
            column: 'parameters'
            type: 'json_array'

        created:
            column: 'created'
            type: 'timepoint'
