'Hal\Core\Entity\Build':
    table: 'jobs_builds'
    repositoryClass: 'Hal\Core\Repository\BuildRepository'
    type: 'entity'

    id:
        id:
            column: id
            type: 'string'
            length: 20

    fields:

        created:
            column: 'created'
            type: 'timepoint'
        start:
            column: 'start'
            type: 'timepoint'
            nullable: true
        end:
            column: 'end'
            type: 'timepoint'
            nullable: true

        status:
            column: 'status'
            type: 'string'
            length: 20
            options: {default: 'pending'} # See JobStatusEnum for list of options

        reference:
            column: 'reference'
            column: 'status'
            type: 'string'
            length: 100
        commit:
            column: 'commit_sha'
            type: 'string'
            length: 40

    manyToOne:

        user:
            cache: {usage : READ_ONLY}
            targetEntity: 'User'
            joinColumn:
                name: 'user_id'
                referencedColumnName: 'id'
                nullable: true

        application:
            cache: {usage : READ_ONLY}
            targetEntity: 'Application'
            joinColumn:
                name: 'application_id'
                referencedColumnName: 'id'
                nullable: true

        environment:
            cache: {usage : READ_ONLY}
            targetEntity: 'Environment'
            joinColumn:
                name: 'environment_id'
                referencedColumnName: 'id'
                nullable: true
