QL\Hal\Core\Entity\Consumer:
    type: entity
    repositoryClass: QL\Hal\Core\Entity\Repository\ConsumerRepository
    table: Consumers

    id:
        id:
            column: ConsumerId
            type: string
            length: 40

    fields:

        key:
            column: ConsumerKey
            type: string
            length: 24
        name:
            column: ConsumerName
            type: string
            length: 48
        secret:
            column: ConsumerSecret
            type: string
            length: 128
        isActive:
            column: ConsumerIsActive
            type: boolean

    oneToMany:

        tokens:
            targetEntity: Token
            mappedBy: consumer
