'Hal\Core\Entity\Credential':
    table: 'credentials'
    type: 'entity'

    cache: {usage : NONSTRICT_READ_WRITE}

    embedded:
        aws:
            class: 'Hal\Core\Entity\Credential\AWSCredential'

        privateKey:
            class: 'Hal\Core\Entity\Credential\PrivateKeyCredential'

    id:
        id:
            column: 'id'
            type: 'guid'

    fields:

        type:
            column: 'type'
            type: 'string'
            length: 20
            options: {default: 'aws'} # See CredentialEnum for list of options

        name:
            column: 'name'
            type: 'string'
            length: 100
