'Hal\Core\Entity\Credential':
    table: 'credentials'
    type: 'entity'

    cache: { usage : NONSTRICT_READ_WRITE }

    embedded:
        awsRole:
            class: 'Hal\Core\Entity\Credential\AWSRoleCredential'
            columnPrefix: false

        awsStatic:
            class: 'Hal\Core\Entity\Credential\AWSStaticCredential'
            columnPrefix: false

        privateKey:
            class: 'Hal\Core\Entity\Credential\PrivateKeyCredential'
            columnPrefix: false
    id:
        id:
            column: 'id'
            type: 'guid'

    fields:

        type:
            column: 'credential_type'
            type: 'string'
            length: 20
            options: { default: 'aws_static' } # See CredentialEnum for list of options

        name:
            column: 'name'
            type: 'string'
            length: 100

        isInternal:
            column: 'is_internal'
            type: 'boolean'
            options: { default: false }

        created:
            column: 'created'
            type: 'timepoint'

    manyToOne:

        application:
            cache: { usage : READ_ONLY }
            targetEntity: 'Application'
            joinColumn:
                name: 'application_id'
                referencedColumnName: 'id'
                nullable: true

        organization:
            cache: { usage : READ_ONLY }
            targetEntity: 'Organization'
            joinColumn:
                name: 'organization_id'
                referencedColumnName: 'id'
                nullable: true

        environment:
            cache: { usage : READ_ONLY }
            targetEntity: 'Environment'
            joinColumn:
                name: 'environment_id'
                referencedColumnName: 'id'
                nullable: true
