'Hal\Core\Entity\Credential':
    table: 'credentials'
    type: 'entity'

    cache: {usage : NONSTRICT_READ_WRITE}

    embedded:
        awsRole:
            class: 'Hal\Core\Entity\Credential\AWSRoleCredential'
            columnPrefix: false

        awsStatic:
            class: 'Hal\Core\Entity\Credential\AWSStaticCredential'
            columnPrefix: false

        privateKey:
            class: 'Hal\Core\Entity\Credential\PrivateKeyCredential'
            columnPrefix: false
    id:
        id:
            column: 'id'
            type: 'guid'

    fields:

        type:
            column: 'type'
            type: 'string'
            length: 20
            options: { default: 'aws_static' } # See CredentialEnum for list of options

        name:
            column: 'name'
            type: 'string'
            length: 100


        isInternal:
            column: 'is_internal'
            type: 'boolean'
            options: { default: false }
