QL\Hal\Core\Entity\EncryptedProperty:
    type: entity
    repositoryClass: QL\Hal\Core\Entity\Repository\EncryptedPropertyRepository
    table: EncryptedProperties

    id:
        id:
            column: EncryptedPropertyId
            type: string
            length: 40

    fields:

        name:
            column: EncryptedPropertyName
            type: string
            length: 128
        data:
            column: EncryptedPropertyData
            type: string

    manyToOne:

        repository:
            targetEntity: Repository
            joinColumn:
                name: RepositoryId
                referencedColumnName: RepositoryId
        environment:
            targetEntity: Environment
            joinColumn:
                name: EnvironmentId
                referencedColumnName: EnvironmentId
                nullable: true
