QL\Hal\Core\Entity\EncryptedProperty:
    type: entity
    table: EncryptedProperties

    cache: {usage : NONSTRICT_READ_WRITE}

    id:
        id:
            column: EncryptedPropertyId
            type: string
            length: 40

    fields:

        name:
            column: EncryptedPropertyName
            type: string
            length: 128
        data:
            column: EncryptedPropertyData
            type: string

    manyToOne:

        application:
            cache: {usage : READ_ONLY}
            targetEntity: Application
            joinColumn:
                name: RepositoryId
                referencedColumnName: RepositoryId

        environment:
            cache: {usage : READ_ONLY}
            targetEntity: Environment
            joinColumn:
                name: EnvironmentId
                referencedColumnName: EnvironmentId
                nullable: true
