'Hal\Core\Entity\Environment':
    table: 'environments'
    repositoryClass: 'Hal\Core\Repository\EnvironmentRepository'
    type: 'entity'

    cache: {usage : NONSTRICT_READ_WRITE}

    id:
        id:
            column: 'id'
            type: 'guid'

    fields:

        name:
            column: 'name'
            type: 'string'
            length: 20
            unique: true
        isProduction:
            column: 'is_production'
            type: 'boolean'
            options: {default: false}
