QL\Hal\Core\Entity\Group:
    type: entity
    table: Groups

    cache: {usage : NONSTRICT_READ_WRITE}

    id:
        id:
            column: GroupId
            type: integer
            generator:
                strategy: AUTO

    fields:

        key:
            column: GroupKey
            type: string
            length: 24
            unique: true
        name:
            column: GroupName
            type: string
            length: 48
