'Hal\Core\Entity\Job':
    table: 'jobs'
    repositoryClass: 'Hal\Core\Repository\JobRepository'
    type: 'entity'

    # http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html
    inheritanceType: JOINED
    discriminatorColumn:
        name: 'job_type'
        type: 'string'
    discriminatorMap:
        build: 'Hal\Core\Entity\JobType\Build'
        release: 'Hal\Core\Entity\JobType\Release'

    id:
        id:
            column: id
            type: 'string'
            length: 20

    fields:

        type:
            column: 'job_type'
            type: 'string'
            length: 50
            options: { default: 'build' } # See JobEnum for list of options

        status:
            column: 'job_status'
            type: 'string'
            length: 50
            options: { default: 'pending' } # See JobStatusEnum for list of options

        parameters:
            column: 'parameters'
            type: 'json_array'

        created:
            column: 'created'
            type: 'timepoint'

        start:
            column: 'start'
            type: 'timepoint'
            nullable: true

        end:
            column: 'job_end'
            type: 'timepoint'
            nullable: true

    oneToMany:

        events:
            targetEntity: 'JobEvent'
            mappedBy: 'job'

        meta:
            targetEntity: 'JobMeta'
            mappedBy: 'job'

    manyToOne:

        user:
            cache: { usage : READ_ONLY }
            targetEntity: 'User'
            joinColumn:
                name: 'user_id'
                referencedColumnName: 'id'
                nullable: true
