'Hal\Core\Entity\JobMeta':
    table: 'jobs_meta'
    type: 'entity'

    cache: {usage : READ_ONLY}

    id:
        id:
            column: 'id'
            type: 'guid'

    fields:

        created:
            column: 'created'
            type: 'timepoint'
        name:
            column: 'name'
            type: 'string'
            length: 100
        value:
            column: 'value'
            type: 'string'

        parent:
            column: 'parent_id'
            type: 'guid'
