'Hal\Core\Entity\Target':
    table: 'targets'
    type: 'entity'

    cache: { usage : NONSTRICT_READ_WRITE }

    id:
        id:
            column: 'id'
            type: 'guid'

    fields:

        type:
            column: 'target_type'
            type: 'string'
            length: 20
            options: { default: 'script' } # See TargetEnum for list of options

        name:
            column: 'name'
            type: 'string'
            length: 100
        url:
            column: 'url'
            type: 'string'
            length: 200

        parameters:
            column: 'parameters'
            type: 'json_array'

        created:
            column: 'created'
            type: 'timepoint'

    manyToOne:

        application:
            cache: { usage : READ_ONLY }
            targetEntity: 'Application'
            joinColumn:
                name: 'application_id'
                referencedColumnName: 'id'
                nullable: false

        environment:
            cache: { usage : READ_ONLY }
            targetEntity: 'Environment'
            joinColumn:
                name: 'environment_id'
                referencedColumnName: 'id'
                nullable: true

        template:
            cache: { usage : READ_ONLY }
            targetEntity: 'TargetTemplate'
            joinColumn:
                name: 'template_id'
                referencedColumnName: 'id'
                nullable: true

        credential:
            cache: { usage : READ_ONLY }
            targetEntity: 'Credential'
            joinColumn:
                name: 'credential_id'
                referencedColumnName: 'id'
                nullable: true

        lastJob:
            cache: { usage : READ_ONLY }
            targetEntity: 'Job'
            joinColumn:
                name: 'last_job_id'
                referencedColumnName: 'id'
                nullable: true
