QL\Kraken\Core\Entity\AuditLog:
    type: entity
    repositoryClass: QL\Kraken\Core\Repository\AuditLogRepository
    table: KrakenAuditLog

    cache: {usage : READ_ONLY}

    id:
        id:
            column: AuditLogID
            type: string
            length: 32
            options: {fixed: true}

    fields:

        created:
            column: AuditLogCreated
            type: timepoint
        entity:
            column: AuditLogEntity
            type: string
            length: 100
        action:
            column: AuditLogAction
            type: string
            length: 20
        data:
            column: AuditLogData
            type: text
            length: 65535

    manyToOne:

        user:
            cache: {usage : READ_ONLY}
            targetEntity: User
            joinColumn:
                name: UserID
                referencedColumnName: UserId
