QL\Kraken\Core\Entity\Environment:
    type: entity
    table: KrakenEnvironment

    cache: {usage : NONSTRICT_READ_WRITE}

    id:
        id:
            column: EnvironmentID
            type: string
            length: 32
            options: {fixed: true}

    fields:

        name:
            column: EnvironmentName
            type: string
            length: 40
        consulServer:
            column: EnvironmentConsulServer
            type: string
            length: 200
        consulToken:
            column: EnvironmentConsulToken
            type: string
            length: 100
        isProduction:
            column: EnvironmentIsProduction
            type: boolean
