QL\Kraken\Core\Entity\Property:
    type: entity
    table: KrakenProperty

    cache: {usage : NONSTRICT_READ_WRITE}

    id:
        id:
            column: PropertyID
            type: string
            length: 32
            options: {fixed: true}

    fields:

        value:
            column: PropertyValue
            type: text
            length: 65535
        created:
            column: PropertyCreated
            type: timepoint
            nullable: true

    manyToOne:

        schema:
            cache: {usage : READ_ONLY}
            targetEntity: Schema
            joinColumn:
                name: SchemaID
                referencedColumnName: SchemaID

        application:
            cache: {usage : READ_ONLY}
            targetEntity: Application
            joinColumn:
                name: ApplicationID
                referencedColumnName: ApplicationID

        environment:
            cache: {usage : READ_ONLY}
            targetEntity: Environment
            joinColumn:
                name: EnvironmentID
                referencedColumnName: EnvironmentID

        user:
            cache: {usage : READ_ONLY}
            targetEntity: QL\Hal\Core\Entity\User
            joinColumn:
                name: UserID
                referencedColumnName: UserId
