QL\Kraken\Core\Entity\Schema:
    type: entity
    table: KrakenSchema

    cache: {usage : NONSTRICT_READ_WRITE}

    id:
        id:
            column: SchemaID
            type: string
            length: 32
            options: {fixed: true}

    fields:

        key:
            column: SchemaKey
            type: string
            length: 150
        dataType:
            column: SchemaDataType
            type: propertyenum
        isSecure:
            column: SchemaIsSecure
            type: boolean
        description:
            column: SchemaDescription
            type: string
            length: 250
        created:
            column: SchemaCreated
            type: timepoint
            nullable: true

    manyToOne:

        application:
            cache: {usage : READ_ONLY}
            targetEntity: Application
            joinColumn:
                name: ApplicationID
                referencedColumnName: ApplicationID

        user:
            cache: {usage : READ_ONLY}
            targetEntity: User
            joinColumn:
                name: UserID
                referencedColumnName: UserId
